version: "3.7"
services:
  producer:
    build: ./producer
    image: xpcoffee/producer
    container_name: producer
    environment:
      AWS_EC2_METADATA_DISABLED: "true"
    ports:
    - 8080:8080
    volumes:
    - ${HOME}/.aws/credentials:/home/.aws/credentials:ro
  consumer:
    build: ./consumer
    image: xpcoffee/consumer
    container_name: consumer
    environment:
      AWS_EC2_METADATA_DISABLED: "true"
    volumes:
    - ${HOME}/.aws/credentials:/home/.aws/credentials:ro